name: CI - Master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  SLS_DEBUG: "*"
  AWSJS_DEBUG: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: npm
    - run: npm ci
    - run: npm run lint
    - run: npm run typecheck
    - run: npm run test
      env:
        AUTHORIZED_ISSUERS_MAP: development
        SIGNING_DID_NAME: ${{ secrets.SIGNING_DID_NAME }}
        SIGNING_DNS_DID_LOCATION: ${{ secrets.SIGNING_DNS_DID_LOCATION }}
        SIGNING_DID: ${{ secrets.SIGNING_DID }}
        SIGNING_DID_KEY: ${{ secrets.SIGNING_DID_KEY }}
        SIGNING_DID_PRIVATE_KEY: ${{ secrets.SIGNING_DID_PRIVATE_KEY }}
    # - run: npm run sls-config-check
  create-new-tag:
    needs: test
    name: Create New Git Tag for release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: master
        DEFAULT_BUMP: patch
  trigger-deploy:
    needs: create-new-tag
    name: trigger deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: ${{ secrets.DEPLOYER_REPO }}
          event-type: ${{ secrets.DEPLOYER_WORKFLOW }}
          client-payload: '{"ref": "${{ github.ref }}"}'