name: ci-pr-open
concurrency: 
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
      - unlocked

env:
  SLS_DEBUG: "*"
  AWSJS_DEBUG: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: npm
    - run: npm ci
    - run: npm run lint
    - run: npm run typecheck
    - run: npm run test
      env:
        AUTHORIZED_ISSUERS_MAP: development
        SIGNING_DID_NAME: ${{ secrets.SIGNING_DID_NAME }}
        SIGNING_DNS_DID_LOCATION: ${{ secrets.SIGNING_DNS_DID_LOCATION }}
        SIGNING_DID: ${{ secrets.SIGNING_DID }}
        SIGNING_DID_KEY: ${{ secrets.SIGNING_DID_KEY }}
        SIGNING_DID_PRIVATE_KEY: ${{ secrets.SIGNING_DID_PRIVATE_KEY }}
  trigger-deploy:
    needs: test
    name: trigger deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository: ${{ secrets.DEPLOYER_REPO }}
          event-type: ci-open
          client-payload: '{"ref": "${{ github.ref }}","stage": "stg-pr-${{ github.event.number }}"}'