name: Sonarqube Scan
concurrency:
  group: sonarqube
  cancel-in-progress: true
  
on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    name: Tests
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - run: npm ci
    - run: npm run lint
    - run: npm run typecheck
    - run: npm run test
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}